version: "3.7"

networks:
  relines_network:
    driver: bridge

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - relines_network

  web:
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    networks:
      - relines_network
